import { TransparentSubmissionData } from './transparent-judging-types';

export const MOCK_TRANSPARENT_SUBMISSIONS: Record<string, TransparentSubmissionData> = {
  'sub_forgezk': {
    submissionId: 'sub_forgezk',
    projectTitle: 'ForgeZK: Verifiable Parallel Rollup Sequencer',
    tagline: 'High-throughput STARK prover pipeline for modular rollups.',
    teamName: 'ByteForge',
    teamSlug: 'byteforge',
    trackName: 'Open Innovation / Systems',
    repositoryUrl: 'https://github.com/byteforge-labs/forge-zk-sequencer',
    demoUrl: 'https://demo.forgezk.network',
    status: 'FINAL',
    finalScore: 93.0,
    maxScore: 100,
    rank: 1,
    totalRanked: 18,
    completedEvaluations: 4,
    requiredEvaluations: 4,
    isPublished: true,
    publishedAt: '2026-09-02T19:00:00.000Z',
    criteriaBreakdown: [
      {
        criterionId: 'crit_tech',
        name: 'Technical Implementation & Architecture',
        description: 'Code quality, system complexity, robust verification, and engineering precision.',
        weight: 0.4,
        weightPercentage: 40,
        rawScore: 38,
        maxRawScore: 40,
        weightedScore: 38.0,
        maxWeightedScore: 40,
        percentageAchieved: 95.0,
      },
      {
        criterionId: 'crit_originality',
        name: 'Originality & Novelty',
        description: 'Uniqueness of approach, creative problem solving, and breakthrough mechanisms.',
        weight: 0.25,
        weightPercentage: 25,
        rawScore: 23.5,
        maxRawScore: 25,
        weightedScore: 23.5,
        maxWeightedScore: 25,
        percentageAchieved: 94.0,
      },
      {
        criterionId: 'crit_impact',
        name: 'Feasibility & Real-world Impact',
        description: 'Practical adoption potential, market utility, and tangible ecosystem value.',
        weight: 0.2,
        weightPercentage: 20,
        rawScore: 18.0,
        maxRawScore: 20,
        weightedScore: 18.0,
        maxWeightedScore: 20,
        percentageAchieved: 90.0,
      },
      {
        criterionId: 'crit_presentation',
        name: 'Documentation & Demo Polish',
        description: 'Clarity of walkthrough pitch, live demo responsiveness, and documentation depth.',
        weight: 0.15,
        weightPercentage: 15,
        rawScore: 13.5,
        maxRawScore: 15,
        weightedScore: 13.5,
        maxWeightedScore: 15,
        percentageAchieved: 90.0,
      },
    ],
    feedbackList: [
      {
        id: 'fb_1',
        reviewerDisplay: 'Verified Reviewer #1',
        reviewerRole: 'Systems & Cryptography Specialist',
        isAnonymized: true,
        submittedAt: '2026-09-02T18:00:00.000Z',
        generalComment:
          'Outstanding engineering rigor. The multithreaded proof scheduling algorithm reduces proof generation latency significantly. Repositories build cleanly with zero warnings.',
        criterionComments: [
          {
            criterionName: 'Technical Implementation',
            comment: 'Clean Rust workspace with comprehensive criterion micro-benchmarks.',
          },
          {
            criterionName: 'Originality',
            comment: 'Novel pipeline chunking model for constraint matrix division.',
          },
        ],
      },
      {
        id: 'fb_2',
        reviewerDisplay: 'Verified Reviewer #2',
        reviewerRole: 'Infrastructure Engineer',
        isAnonymized: true,
        submittedAt: '2026-09-02T18:30:00.000Z',
        generalComment:
          'Live testnet demo worked smoothly without dropped blocks. Very crisp documentation with clear architectural diagrams.',
        criterionComments: [
          {
            criterionName: 'Presentation',
            comment: 'High production quality walkthrough video and interactive explorer.',
          },
        ],
      },
    ],
    timeline: [
      {
        id: 'tl_1',
        title: 'Submission Verified & Locked',
        timestamp: '2026-09-02T16:00:00.000Z',
        status: 'COMPLETED',
        description: 'Git commit snapshot locked and automated test verification completed.',
      },
      {
        id: 'tl_2',
        title: 'Independent Reviewer Evaluations',
        timestamp: '2026-09-02T18:30:00.000Z',
        status: 'COMPLETED',
        description: '4 independent judge evaluations completed according to published rubric.',
      },
      {
        id: 'tl_3',
        title: 'Calibrated Score Consensus',
        timestamp: '2026-09-02T18:50:00.000Z',
        status: 'COMPLETED',
        description: 'Evaluation variance normalized through outlier detection and calibration.',
      },
      {
        id: 'tl_4',
        title: 'Results Certified & Published',
        timestamp: '2026-09-02T19:00:00.000Z',
        status: 'COMPLETED',
        description: 'Scores finalized and published to participant transparency portal.',
      },
    ],
    guarantees: {
      isAnonymized: true,
      criteriaAuditVerified: true,
      weightsNormalized: true,
      calibrationApplied: true,
    },
  },
  'sub_neuralaudit': {
    submissionId: 'sub_neuralaudit',
    projectTitle: 'NeuralAudit: Multi-Agent Formal Verification Engine',
    tagline: 'Autonomous AI agents collaborating on smart contract vulnerability analysis.',
    teamName: 'NeuralGuard',
    teamSlug: 'neuralguard',
    trackName: 'AI Safety & Intelligent Workflows',
    repositoryUrl: 'https://github.com/neuralguard/neural-audit-agent',
    demoUrl: 'https://app.neuralaudit.ai',
    status: 'FINAL',
    finalScore: 85.0,
    maxScore: 100,
    rank: 2,
    totalRanked: 18,
    completedEvaluations: 4,
    requiredEvaluations: 4,
    isPublished: true,
    publishedAt: '2026-09-02T19:00:00.000Z',
    criteriaBreakdown: [
      {
        criterionId: 'crit_tech',
        name: 'Technical Implementation & Architecture',
        description: 'Code quality, system complexity, robust verification, and engineering precision.',
        weight: 0.4,
        weightPercentage: 40,
        rawScore: 34,
        maxRawScore: 40,
        weightedScore: 34.0,
        maxWeightedScore: 40,
        percentageAchieved: 85.0,
      },
      {
        criterionId: 'crit_originality',
        name: 'Originality & Novelty',
        description: 'Uniqueness of approach, creative problem solving, and breakthrough mechanisms.',
        weight: 0.25,
        weightPercentage: 25,
        rawScore: 22.5,
        maxRawScore: 25,
        weightedScore: 22.5,
        maxWeightedScore: 25,
        percentageAchieved: 90.0,
      },
      {
        criterionId: 'crit_impact',
        name: 'Feasibility & Real-world Impact',
        description: 'Practical adoption potential, market utility, and tangible ecosystem value.',
        weight: 0.2,
        weightPercentage: 20,
        rawScore: 16.5,
        maxRawScore: 20,
        weightedScore: 16.5,
        maxWeightedScore: 20,
        percentageAchieved: 82.5,
      },
      {
        criterionId: 'crit_presentation',
        name: 'Documentation & Demo Polish',
        description: 'Clarity of walkthrough pitch, live demo responsiveness, and documentation depth.',
        weight: 0.15,
        weightPercentage: 15,
        rawScore: 12.0,
        maxRawScore: 15,
        weightedScore: 12.0,
        maxWeightedScore: 15,
        percentageAchieved: 80.0,
      },
    ],
    feedbackList: [
      {
        id: 'fb_na_1',
        reviewerDisplay: 'Verified Reviewer #1',
        reviewerRole: 'AI & Security Auditor',
        isAnonymized: true,
        submittedAt: '2026-09-02T18:15:00.000Z',
        generalComment:
          'Impressive multi-agent orchestration for detecting reentrancy and arithmetic underflow conditions. Recommend expanding test suites for cross-contract interactions.',
        criterionComments: [
          {
            criterionName: 'Originality',
            comment: 'Great use of debate-style verification between adversarial agents.',
          },
        ],
      },
    ],
    timeline: [
      {
        id: 'tl_1',
        title: 'Submission Verified & Locked',
        timestamp: '2026-09-02T16:00:00.000Z',
        status: 'COMPLETED',
        description: 'Git commit snapshot locked and automated test verification completed.',
      },
      {
        id: 'tl_2',
        title: 'Independent Reviewer Evaluations',
        timestamp: '2026-09-02T18:45:00.000Z',
        status: 'COMPLETED',
        description: '4 independent judge evaluations completed according to published rubric.',
      },
      {
        id: 'tl_3',
        title: 'Calibrated Score Consensus',
        timestamp: '2026-09-02T18:55:00.000Z',
        status: 'COMPLETED',
        description: 'Evaluation variance normalized through outlier detection and calibration.',
      },
      {
        id: 'tl_4',
        title: 'Results Certified & Published',
        timestamp: '2026-09-02T19:00:00.000Z',
        status: 'COMPLETED',
        description: 'Scores finalized and published to participant transparency portal.',
      },
    ],
    guarantees: {
      isAnonymized: true,
      criteriaAuditVerified: true,
      weightsNormalized: true,
      calibrationApplied: true,
    },
  },
  'sub_sentinelnet': {
    submissionId: 'sub_sentinelnet',
    projectTitle: 'SentinelNet: Decentralized Verifiable Uptime Oracles',
    tagline: 'Trustless hardware telemetry for decentralized physical infrastructure.',
    teamName: 'DePIN Sentinel',
    teamSlug: 'depin-sentinel',
    trackName: 'Open Innovation / Systems',
    repositoryUrl: 'https://github.com/sentinelnet/depin-uptime-oracle',
    demoUrl: 'https://sentinelnet.network',
    status: 'PROVISIONAL',
    finalScore: 85.0,
    maxScore: 100,
    completedEvaluations: 2,
    requiredEvaluations: 4,
    isPublished: false,
    criteriaBreakdown: [
      {
        criterionId: 'crit_tech',
        name: 'Technical Implementation & Architecture',
        description: 'Code quality, system complexity, robust verification, and engineering precision.',
        weight: 0.4,
        weightPercentage: 40,
        rawScore: 34,
        maxRawScore: 40,
        weightedScore: 34.0,
        maxWeightedScore: 40,
        percentageAchieved: 85.0,
      },
      {
        criterionId: 'crit_originality',
        name: 'Originality & Novelty',
        description: 'Uniqueness of approach, creative problem solving, and breakthrough mechanisms.',
        weight: 0.25,
        weightPercentage: 25,
        rawScore: 21.0,
        maxRawScore: 25,
        weightedScore: 21.0,
        maxWeightedScore: 25,
        percentageAchieved: 84.0,
      },
      {
        criterionId: 'crit_impact',
        name: 'Feasibility & Real-world Impact',
        description: 'Practical adoption potential, market utility, and tangible ecosystem value.',
        weight: 0.2,
        weightPercentage: 20,
        rawScore: 17.5,
        maxRawScore: 20,
        weightedScore: 17.5,
        maxWeightedScore: 20,
        percentageAchieved: 87.5,
      },
      {
        criterionId: 'crit_presentation',
        name: 'Documentation & Demo Polish',
        description: 'Clarity of walkthrough pitch, live demo responsiveness, and documentation depth.',
        weight: 0.15,
        weightPercentage: 15,
        rawScore: 12.5,
        maxRawScore: 15,
        weightedScore: 12.5,
        maxWeightedScore: 15,
        percentageAchieved: 83.3,
      },
    ],
    feedbackList: [
      {
        id: 'fb_sn_1',
        reviewerDisplay: 'Verified Reviewer #1',
        reviewerRole: 'DePIN Systems Specialist',
        isAnonymized: true,
        submittedAt: '2026-09-02T18:10:00.000Z',
        generalComment:
          'Strong hardware oracle prototype with verifiable secure enclave signatures. Evaluating remaining rounds.',
        criterionComments: [],
      },
    ],
    timeline: [
      {
        id: 'tl_1',
        title: 'Submission Verified & Locked',
        timestamp: '2026-09-02T16:00:00.000Z',
        status: 'COMPLETED',
        description: 'Git commit snapshot locked and automated test verification completed.',
      },
      {
        id: 'tl_2',
        title: 'Independent Reviewer Evaluations',
        status: 'IN_PROGRESS',
        description: '2 of 4 evaluations completed. Judging is currently active.',
      },
      {
        id: 'tl_3',
        title: 'Calibrated Score Consensus',
        status: 'PENDING',
        description: 'Awaiting completion of all reviewer rounds.',
      },
      {
        id: 'tl_4',
        title: 'Results Certified & Published',
        status: 'PENDING',
        description: 'Scores will be finalized once judging phase concludes.',
      },
    ],
    guarantees: {
      isAnonymized: true,
      criteriaAuditVerified: true,
      weightsNormalized: true,
      calibrationApplied: false,
    },
  },
};
