import { CertificateItem, CertificateSummaryMetrics } from './certificates-types';

export const MOCK_CERTIFICATES: CertificateItem[] = [
  {
    id: 'cert_1',
    hackathonId: 'htf-2026',
    hackathonName: 'Hack The Future 2026',
    participantId: 'usr_alex_sharma',
    participantName: 'Alex Sharma',
    participantEmail: 'alex.sharma@byteforge.dev',
    participantAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    teamId: 'team_byteforge',
    teamName: 'ByteForge',
    type: 'WINNER',
    title: 'Certificate of Excellence — 1st Place Grand Champion',
    status: 'ISSUED',
    issuedAt: '2026-09-02T18:00:00.000Z',
    verificationId: 'AH-2026-ZK914A',
    verificationUrl: 'https://almosthack.dev/verify/AH-2026-ZK914A',
    signatureHash: '0x8f9c1b3e4a2d7f8812c9b4e6d3a1f7c89b2e4d6a',
    awardName: '1st Place — Grand Champion',
    trackName: 'Open Innovation / Systems',
    pdfUrl: '/api/v1/certificates/cert_1/download',
  },
  {
    id: 'cert_2',
    hackathonId: 'htf-2026',
    hackathonName: 'Hack The Future 2026',
    participantId: 'usr_priya_patel',
    participantName: 'Priya Patel',
    participantEmail: 'priya@neuralguard.ai',
    participantAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    teamId: 'team_neuralguard',
    teamName: 'NeuralGuard',
    type: 'TRACK_WINNER',
    title: 'Certificate of Distinction — Best AI & Security Innovation',
    status: 'ISSUED',
    issuedAt: '2026-09-02T18:00:00.000Z',
    verificationId: 'AH-2026-AI772B',
    verificationUrl: 'https://almosthack.dev/verify/AH-2026-AI772B',
    signatureHash: '0x3c7e9a1b5f8d2e4c6b8a0f9e1d3c5b7a9f2e4d6c',
    awardName: 'Best AI & Security Innovation',
    trackName: 'AI Safety & Intelligent Workflows',
    pdfUrl: '/api/v1/certificates/cert_2/download',
  },
  {
    id: 'cert_3',
    hackathonId: 'htf-2026',
    hackathonName: 'Hack The Future 2026',
    participantId: 'usr_marcus_vance',
    participantName: 'Marcus Vance',
    participantEmail: 'marcus@depinsentinel.net',
    teamId: 'team_depin',
    teamName: 'DePIN Sentinel',
    type: 'WINNER',
    title: 'Certificate of Excellence — 3rd Place Overall',
    status: 'ISSUED',
    issuedAt: '2026-09-02T18:00:00.000Z',
    verificationId: 'AH-2026-DP451C',
    verificationUrl: 'https://almosthack.dev/verify/AH-2026-DP451C',
    signatureHash: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
    awardName: '3rd Place',
    trackName: 'Open Innovation / Systems',
    pdfUrl: '/api/v1/certificates/cert_3/download',
  },
  {
    id: 'cert_4',
    hackathonId: 'htf-2026',
    hackathonName: 'Hack The Future 2026',
    participantId: 'usr_elena_rostova',
    participantName: 'Elena Rostova',
    participantEmail: 'elena@zerotrace.org',
    teamId: 'team_zerotrace',
    teamName: 'ZeroTrace Privacy',
    type: 'FINALIST',
    title: 'Certificate of Achievement — Official Finalist',
    status: 'ISSUED',
    issuedAt: '2026-09-02T18:00:00.000Z',
    verificationId: 'AH-2026-FN883D',
    verificationUrl: 'https://almosthack.dev/verify/AH-2026-FN883D',
    signatureHash: '0x5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f',
    trackName: 'Open Innovation / Systems',
    pdfUrl: '/api/v1/certificates/cert_4/download',
  },
  {
    id: 'cert_5',
    hackathonId: 'htf-2026',
    hackathonName: 'Hack The Future 2026',
    participantId: 'usr_david_kim',
    participantName: 'David Kim',
    participantEmail: 'david.kim@nexuslabs.io',
    teamId: 'team_nexus',
    teamName: 'Nexus Labs',
    type: 'PARTICIPATION',
    title: 'Certificate of Participation',
    status: 'ISSUED',
    issuedAt: '2026-09-02T18:00:00.000Z',
    verificationId: 'AH-2026-PT102E',
    verificationUrl: 'https://almosthack.dev/verify/AH-2026-PT102E',
    signatureHash: '0x9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b',
    trackName: 'Open Innovation / Systems',
    pdfUrl: '/api/v1/certificates/cert_5/download',
  },
  {
    id: 'cert_6',
    hackathonId: 'htf-2026',
    hackathonName: 'Hack The Future 2026',
    participantId: 'usr_sarah_jenkins',
    participantName: 'Sarah Jenkins',
    participantEmail: 'sarah.j@omnirollup.dev',
    teamId: 'team_omni',
    teamName: 'OmniRollup',
    type: 'PARTICIPATION',
    title: 'Certificate of Participation',
    status: 'PENDING',
    verificationId: 'AH-2026-PT309F',
    verificationUrl: 'https://almosthack.dev/verify/AH-2026-PT309F',
    signatureHash: '0x0000000000000000000000000000000000000000',
    trackName: 'Open Innovation / Systems',
  },
  {
    id: 'cert_7',
    hackathonId: 'htf-2026',
    hackathonName: 'Hack The Future 2026',
    participantId: 'usr_lucas_silva',
    participantName: 'Lucas Silva',
    participantEmail: 'lucas.silva@zkbridge.xyz',
    teamId: 'team_zkbridge',
    teamName: 'ZK Bridge',
    type: 'PARTICIPATION',
    title: 'Certificate of Participation',
    status: 'FAILED',
    verificationId: 'AH-2026-PT990G',
    verificationUrl: 'https://almosthack.dev/verify/AH-2026-PT990G',
    signatureHash: '0x0000000000000000000000000000000000000000',
    failureReason: 'Missing verified GitHub commit telemetry for project submission.',
  },
  {
    id: 'cert_8',
    hackathonId: 'htf-2026',
    hackathonName: 'Hack The Future 2026',
    participantId: 'usr_frank_miller',
    participantName: 'Frank Miller',
    participantEmail: 'frank.m@sybilnet.io',
    teamId: 'team_sybil',
    teamName: 'Sybil Test Team',
    type: 'PARTICIPATION',
    title: 'Certificate of Participation',
    status: 'REVOKED',
    issuedAt: '2026-09-02T17:00:00.000Z',
    revokedAt: '2026-09-02T19:30:00.000Z',
    revocationReason: 'Disqualified by organizer committee due to terms of service violation.',
    verificationId: 'AH-2026-PT001R',
    verificationUrl: 'https://almosthack.dev/verify/AH-2026-PT001R',
    signatureHash: '0xrevoked000000000000000000000000000000000',
  },
];

export const MOCK_CERTIFICATE_SUMMARY: CertificateSummaryMetrics = {
  totalEligible: 84,
  totalIssued: 80,
  totalPending: 2,
  totalGenerating: 1,
  totalFailed: 1,
  totalRevoked: 1,
};
