import {
  HackathonEntity,
  TeamEntity,
  SubmissionEntity,
  JudgingCriterionEntity,
  AnnouncementEntity,
  AnnouncementStatus,
  AnnouncementRecipientScope,
  TeamMemberRole,
  TeamMemberStatus,
  TeamStatus,
  HackathonStatus,
  HackathonVisibility,
} from '@almosthack/types';
import { CertificateItem } from '../certificates/certificates-types';

export const MOCK_HACKER_HACKATHONS: HackathonEntity[] = [
  {
    id: 'htf-2026',
    organizationId: 'org_almosthack',
    name: 'Hack The Future 2026',
    slug: 'hack-the-future-2026',
    description:
      'The premier global hackathon for decentralized infrastructure, autonomous agents, and zero-knowledge cryptography.',
    logoUrl: null,
    websiteUrl: 'https://almosthack.io/htf-2026',
    timezone: 'Asia/Kolkata',
    status: HackathonStatus.LIVE,
    visibility: HackathonVisibility.PUBLIC,
    registrationStartsAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    registrationEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    startsAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    endsAt: new Date(Date.now() + 1000 * 60 * 60 * 48 + 1000 * 60 * 32).toISOString(),
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    completedAt: null,
    archivedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'agentic-ai-2026',
    organizationId: 'org_almosthack',
    name: 'Global Agentic AI Hackathon',
    slug: 'agentic-ai-2026',
    description:
      'Autonomous swarms, multi-agent reasoning systems, and LLM orchestration protocols.',
    logoUrl: null,
    websiteUrl: 'https://almosthack.io/agentic-ai-2026',
    timezone: 'UTC',
    status: HackathonStatus.PUBLISHED,
    visibility: HackathonVisibility.PUBLIC,
    registrationStartsAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    registrationEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10).toISOString(),
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 12).toISOString(),
    endsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14).toISOString(),
    publishedAt: new Date().toISOString(),
    completedAt: null,
    archivedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_HACKER_TEAM: TeamEntity = {
  id: 'team_byteforge',
  hackathonId: 'htf-2026',
  name: 'ByteForge Squad',
  slug: 'byteforge-squad',
  description: 'Building high-throughput state synchronization protocols.',
  createdByUserId: 'usr_hacker_current',
  status: TeamStatus.ACTIVE,
  memberCount: 3,
  createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  updatedAt: new Date().toISOString(),
  members: [
    {
      id: 'mem_01',
      teamId: 'team_byteforge',
      userId: 'usr_hacker_current',
      role: TeamMemberRole.CAPTAIN,
      status: TeamMemberStatus.ACTIVE,
      joinedAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
      leftAt: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      user: {
        id: 'usr_hacker_current',
        name: 'Alex Vance (You)',
        email: 'alex.vance@builder.io',
        avatarUrl: null,
        college: null,
        branch: null,
        skills: ['Rust', 'Distributed Systems'],
      },
    },
    {
      id: 'mem_02',
      teamId: 'team_byteforge',
      userId: 'usr_hacker_aditi',
      role: TeamMemberRole.MEMBER,
      status: TeamMemberStatus.ACTIVE,
      joinedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      leftAt: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      user: {
        id: 'usr_hacker_aditi',
        name: 'Aditi Sharma',
        email: 'aditi.s@dev.net',
        avatarUrl: null,
        college: null,
        branch: null,
        skills: ['TypeScript', 'Solidity'],
      },
    },
    {
      id: 'mem_03',
      teamId: 'team_byteforge',
      userId: 'usr_hacker_arjun',
      role: TeamMemberRole.MEMBER,
      status: TeamMemberStatus.ACTIVE,
      joinedAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
      leftAt: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      user: {
        id: 'usr_hacker_arjun',
        name: 'Arjun Mehta',
        email: 'arjun.m@kernel.org',
        avatarUrl: null,
        college: null,
        branch: null,
        skills: ['Go', 'WASM'],
      },
    },
  ],
  invitations: [
    {
      id: 'inv_out_01',
      teamId: 'team_byteforge',
      inviteeUserId: 'usr_invitee_sarah',
      invitedByUserId: 'usr_hacker_current',
      status: 'PENDING' as any,
      expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
      respondedAt: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      inviteeUser: {
        id: 'usr_invitee_sarah',
        name: 'Sarah Chen',
        email: 'sarah.c@security.io',
        avatarUrl: null,
        college: null,
        branch: null,
        skills: ['Security', 'Formal Verification'],
      },
    },
  ],
};

export const MOCK_INCOMING_INVITATIONS = [
  {
    id: 'inv_inc_01',
    teamId: 'team_neuralsync',
    inviteeUserId: 'usr_hacker_current',
    invitedByUserId: 'usr_lead_marcus',
    status: 'PENDING' as any,
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    respondedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    team: {
      id: 'team_neuralsync',
      hackathonId: 'htf-2026',
      name: 'NeuralSync Labs',
      slug: 'neuralsync-labs',
      description: 'Distributed neural weights aggregation over P2P libp2p networks.',
      createdByUserId: 'usr_lead_marcus',
      status: TeamStatus.ACTIVE,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      memberCount: 2,
    },
    invitedByUser: {
      id: 'usr_lead_marcus',
      name: 'Marcus Brody',
      email: 'marcus@neuralsync.ai',
      avatarUrl: null,
      college: null,
      branch: null,
      skills: ['Python', 'PyTorch'],
    },
  },
];

export const MOCK_HACKER_SUBMISSION: SubmissionEntity = {
  id: 'sub_byteforge_01',
  hackathonId: 'htf-2026',
  teamId: 'team_byteforge',
  title: 'ByteForge: Real-Time Decentralized State Sync',
  description:
    'ByteForge is a zero-latency distributed state verification protocol. We implemented custom WASM execution containers and a verifiable DAG memory engine that cuts synchronization latency by 85% compared to standard optimistic rollups.',
  trackId: 'trk_core_infra',
  status: 'DRAFT',
  commitSha: '7f9c2a1e4b3d8c9a0f1e2d3c4b5a6f7e8d9c0b1a',
  demoUrl: 'https://byteforge-demo.vercel.app',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  team: {
    id: 'team_byteforge',
    name: 'ByteForge Squad',
    slug: 'byteforge-squad',
  },
  track: {
    id: 'trk_core_infra',
    name: 'Core Infrastructure',
  },
  repository: {
    id: 'repo_01',
    repositoryFullName: 'byteforge/byteforge-core',
    repositoryUrl: 'https://github.com/byteforge/byteforge-core',
    defaultBranch: 'main',
  },
};

export const MOCK_HACKER_ANNOUNCEMENTS: AnnouncementEntity[] = [
  {
    id: 'ann_01',
    hackathonId: 'htf-2026',
    organizationId: 'org_almosthack',
    authorId: 'usr_organizer_lead',
    title: 'Final Submission Deadline & Video Upload Guidelines',
    body: 'All teams must submit their final project repository commit SHA and live demo URL before Sep 5, 11:59 PM IST. Ensure your repository permissions are public or organization-accessible.',
    status: AnnouncementStatus.PUBLISHED,
    recipientScope: AnnouncementRecipientScope.ALL_PARTICIPANTS,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ann_02',
    hackathonId: 'htf-2026',
    organizationId: 'org_almosthack',
    authorId: 'usr_organizer_lead',
    title: 'Live Mentorship Office Hours for Zero-Knowledge Circuits',
    body: 'Join our core cryptography sponsors on Discord channel #zk-mentorship for 1-on-1 code reviews and proof optimization advice.',
    status: AnnouncementStatus.PUBLISHED,
    recipientScope: AnnouncementRecipientScope.ALL_PARTICIPANTS,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_HACKER_CERTIFICATES: CertificateItem[] = [
  {
    id: 'cert_participant_01',
    hackathonId: 'htf-2026',
    hackathonName: 'Hack The Future 2026',
    participantId: 'usr_hacker_current',
    participantName: 'Alex Vance',
    participantEmail: 'alex.vance@builder.io',
    teamId: 'team_byteforge',
    teamName: 'ByteForge Squad',
    type: 'PARTICIPATION',
    title: 'Verified Participant Credential',
    status: 'ISSUED',
    verificationId: 'AH-2026-HTF-90214',
    signatureHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    verificationUrl: 'https://almosthack.io/verify/AH-2026-HTF-90214',
    trackName: 'Core Infrastructure',
    issuedAt: new Date().toISOString(),
  },
];
