import {
  AuditLogItem,
  AuditLogMetrics,
  AuditLogActor,
} from './audit-log-types';

export const KNOWN_ACTORS: AuditLogActor[] = [
  {
    id: 'usr_alex',
    name: 'Alex Sharma',
    email: 'lead@alexlabs.dev',
    role: 'Lead Organizer',
    avatarUrl: '',
    isSystem: false,
  },
  {
    id: 'usr_priya',
    name: 'Priya Sharma',
    email: 'priya@alexlabs.dev',
    role: 'Track Organizer',
    avatarUrl: '',
    isSystem: false,
  },
  {
    id: 'usr_aris',
    name: 'Dr. Aris Thorne',
    email: 'aris.thorne@cambridge.ac.uk',
    role: 'Lead Judge',
    avatarUrl: '',
    isSystem: false,
  },
  {
    id: 'usr_marcus',
    name: 'Marcus Vance',
    email: 'marcus@depin.net',
    role: 'Domain Judge',
    avatarUrl: '',
    isSystem: false,
  },
  {
    id: 'sys_automation',
    name: 'AlmostHack Integrity Engine',
    email: 'system.engine@almosthack.io',
    role: 'Automated Service',
    avatarUrl: '',
    isSystem: true,
  },
];

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'aud_98a7f6c1',
    hackathonId: 'htf-2026',
    organizationId: 'org_alex_labs',
    actorId: 'usr_alex',
    actorEmail: 'lead@alexlabs.dev',
    actor: KNOWN_ACTORS[0],
    action: 'certificate.revoked',
    actionLabel: 'Revoked Participant Digital Credential',
    targetEntity: 'CERTIFICATE',
    targetId: 'AH-2026-PT001R',
    targetLabel: 'Certificate #AH-2026-PT001R (Frank Miller)',
    targetUrl: '/certificates/AH-2026-PT001R',
    diffs: [
      {
        field: 'status',
        label: 'Credential Status',
        before: 'ISSUED',
        after: 'REVOKED',
      },
      {
        field: 'revocationReason',
        label: 'Revocation Audit Reason',
        before: null,
        after: 'Violation of hackathon terms: pre-built codebase submitted',
      },
    ],
    metadata: {
      revocationReason: 'Violation of hackathon terms: pre-built codebase submitted',
      certificateId: 'cert_3',
      participantName: 'Frank Miller',
    },
    ipAddress: '192.168.1.104',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    checksum: '0x8f9c1b3e4a2d7f8812c9b4e6d3a1f7c89b2e4d6a',
    createdAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: 'aud_87b6e5d2',
    hackathonId: 'htf-2026',
    organizationId: 'org_alex_labs',
    actorId: 'usr_alex',
    actorEmail: 'lead@alexlabs.dev',
    actor: KNOWN_ACTORS[0],
    action: 'results.published',
    actionLabel: 'Published Official Results & Leaderboard',
    targetEntity: 'RESULT',
    targetId: 'res_htf_2026',
    targetLabel: 'Official Leaderboard & Winner Allocation',
    targetUrl: '/hackathons/htf-2026/results',
    diffs: [
      {
        field: 'status',
        label: 'Results Lifecycle Status',
        before: 'APPROVED',
        after: 'PUBLISHED',
      },
      {
        field: 'publishedToParticipants',
        label: 'Participant Visibility',
        before: false,
        after: true,
      },
    ],
    metadata: {
      totalSubmissionsRanked: 84,
      grandChampion: 'ByteForge (Alex Sharma)',
    },
    ipAddress: '192.168.1.104',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    checksum: '0x4e2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c',
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'aud_76a5d4c3',
    hackathonId: 'htf-2026',
    organizationId: 'org_alex_labs',
    actorId: 'usr_aris',
    actorEmail: 'aris.thorne@cambridge.ac.uk',
    actor: KNOWN_ACTORS[2],
    action: 'judging.score_submitted',
    actionLabel: 'Submitted Review Evaluation Score',
    targetEntity: 'EVALUATION',
    targetId: 'eval_8492_aris',
    targetLabel: 'Submission: ByteForge (Score: 86.5)',
    targetUrl: '/hackathons/htf-2026/submissions',
    diffs: [
      {
        field: 'technicalScore',
        label: 'Technical Architecture Score',
        before: null,
        after: 28,
      },
      {
        field: 'innovationScore',
        label: 'Innovation & Impact Score',
        before: null,
        after: 23,
      },
      {
        field: 'totalScore',
        label: 'Calibrated Total Score',
        before: null,
        after: 86.5,
      },
    ],
    metadata: {
      submissionId: 'sub_01',
      teamName: 'ByteForge',
      judgeRole: 'Systems Lead',
    },
    ipAddress: '131.111.8.42',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    checksum: '0x9a8f7c6b5a4e3d2c1b0a7f8e9d0c1b2a3e4f5a6b',
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'aud_65b4c3b4',
    hackathonId: 'htf-2026',
    organizationId: 'org_alex_labs',
    actorId: 'usr_alex',
    actorEmail: 'lead@alexlabs.dev',
    actor: KNOWN_ACTORS[0],
    action: 'announcement.published',
    actionLabel: 'Broadcast Event Announcement',
    targetEntity: 'ANNOUNCEMENT',
    targetId: 'ann_01',
    targetLabel: 'Final 6 Hours: Submission Window Closing',
    targetUrl: '/hackathons/htf-2026/announcements',
    diffs: [
      {
        field: 'status',
        label: 'Broadcast Status',
        before: 'DRAFT',
        after: 'PUBLISHED',
      },
      {
        field: 'recipientScope',
        label: 'Audience Scope',
        before: 'ALL_PARTICIPANTS',
        after: 'ALL_PARTICIPANTS',
      },
    ],
    metadata: {
      recipientsNotified: 1080,
    },
    ipAddress: '192.168.1.104',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    checksum: '0x3c7e9a1b5f8d2e4c6b8a0f9e1d3c5b7a9f2e4d6c',
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 'aud_54a3b2a5',
    hackathonId: 'htf-2026',
    organizationId: 'org_alex_labs',
    actorId: 'sys_automation',
    actorEmail: 'system.engine@almosthack.io',
    actor: KNOWN_ACTORS[4],
    action: 'submission.integrity_verified',
    actionLabel: 'Executed Automated Repository Integrity Scan',
    targetEntity: 'SUBMISSION',
    targetId: 'sub_02',
    targetLabel: 'Submission: NeuralGuard (neuralguard/neural-audit)',
    targetUrl: '/hackathons/htf-2026/submissions',
    diffs: [
      {
        field: 'integrityStatus',
        label: 'Integrity Status',
        before: 'PENDING_SCAN',
        after: 'VERIFIED_CLEAN',
      },
      {
        field: 'commitShaVerified',
        label: 'Commit SHA Hash',
        before: null,
        after: '7f9c2a1',
      },
    ],
    metadata: {
      matchedFiles: 0,
      similarityScore: 0.04,
      result: 'CLEAN',
    },
    ipAddress: '10.0.4.12',
    userAgent: 'AlmostHack-IntegrityEngine/1.0.0',
    checksum: '0x1d3c5b7a9f2e4d6c8b0a7f9e1c3b5a7f9e2d4c6a',
    createdAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
  {
    id: 'aud_43a2b1a6',
    hackathonId: 'htf-2026',
    organizationId: 'org_alex_labs',
    actorId: 'usr_priya',
    actorEmail: 'priya@alexlabs.dev',
    actor: KNOWN_ACTORS[1],
    action: 'participant.approved',
    actionLabel: 'Approved Builder Registration',
    targetEntity: 'PARTICIPANT',
    targetId: 'usr_rahul_99',
    targetLabel: 'Participant: Rahul Sharma (rahul.s@iitd.ac.in)',
    targetUrl: '/hackathons/htf-2026/registrations',
    diffs: [
      {
        field: 'registrationStatus',
        label: 'Registration Status',
        before: 'PENDING_REVIEW',
        after: 'APPROVED',
      },
    ],
    metadata: {
      githubUsername: 'rahulsharma-dev',
      trackPreference: 'AI Safety',
    },
    ipAddress: '172.16.4.18',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    checksum: '0x7b6a5f4e3d2c1b0a9f8e2d4c6b8a0f9e1d3c5b7a',
    createdAt: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
  },
  {
    id: 'aud_32a1b0a7',
    hackathonId: 'htf-2026',
    organizationId: 'org_alex_labs',
    actorId: 'usr_alex',
    actorEmail: 'lead@alexlabs.dev',
    actor: KNOWN_ACTORS[0],
    action: 'hackathon.configuration_updated',
    actionLabel: 'Updated Hackathon Schedule & Parameters',
    targetEntity: 'HACKATHON',
    targetId: 'htf-2026',
    targetLabel: 'Hack The Future 2026 Configuration',
    targetUrl: '/hackathons/htf-2026/configuration',
    diffs: [
      {
        field: 'submissionDeadline',
        label: 'Submission Deadline',
        before: '2026-09-02T18:00:00.000Z',
        after: '2026-09-02T23:59:59.000Z',
      },
      {
        field: 'maxTeamSize',
        label: 'Maximum Team Size',
        before: 4,
        after: 4,
      },
    ],
    metadata: {
      reason: 'Accommodate late timezone participants with 6h extension',
    },
    ipAddress: '192.168.1.104',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    checksum: '0x5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e',
    createdAt: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
  },
];

export const MOCK_AUDIT_METRICS: AuditLogMetrics = {
  totalEvents: 284,
  configEvents: 18,
  participantTeamEvents: 142,
  judgingEvents: 84,
  credentialBroadcastEvents: 40,
};
