import { TeamItem, UnassignedParticipantItem, TeamMetrics } from './teams-types';

export const MOCK_TEAMS: TeamItem[] = [
  {
    id: 'team_byteforge',
    hackathonId: 'htf-2026',
    name: 'ByteForge',
    slug: 'byteforge',
    description: 'High-throughput verifiable execution layer on decentralized state machines.',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    status: 'ACTIVE',
    sizeStatus: 'FULL',
    memberCount: 4,
    minTeamSize: 2,
    maxTeamSize: 4,
    captain: {
      id: 'mem_1',
      userId: 'usr_aarav',
      name: 'Aarav Sharma',
      email: 'aarav.sharma@iitd.ac.in',
    },
    members: [
      {
        id: 'mem_1',
        userId: 'usr_aarav',
        name: 'Aarav Sharma',
        username: 'aarav_sharma',
        email: 'aarav.sharma@iitd.ac.in',
        college: 'IIT Delhi',
        branch: 'Computer Science and Engineering',
        skills: ['Rust', 'Distributed Systems', 'Solidity'],
        role: 'CAPTAIN',
        status: 'ACTIVE',
        joinedAt: '2026-09-01T10:30:00.000Z',
      },
      {
        id: 'mem_2',
        userId: 'usr_ananya',
        name: 'Ananya Iyer',
        username: 'ananya_ux',
        email: 'ananya.iyer@nitt.edu',
        college: 'NIT Trichy',
        branch: 'Information Technology',
        skills: ['React', 'Next.js', 'TailwindCSS', 'TypeScript'],
        role: 'MEMBER',
        status: 'ACTIVE',
        joinedAt: '2026-09-01T12:00:00.000Z',
      },
      {
        id: 'mem_3',
        userId: 'usr_dev',
        name: 'Devika Krishnan',
        username: 'devika_k',
        email: 'devika.krishnan@iitk.ac.in',
        college: 'IIT Kanpur',
        branch: 'Computer Science & Mathematics',
        skills: ['ZK-Rollups', 'Rust', 'Circom'],
        role: 'MEMBER',
        status: 'ACTIVE',
        joinedAt: '2026-09-01T14:15:00.000Z',
      },
      {
        id: 'mem_4',
        userId: 'usr_siddharth',
        name: 'Siddharth Roy',
        username: 'sid_roy',
        email: 'sid.roy@bits-goa.ac.in',
        college: 'BITS Goa',
        branch: 'Computer Science',
        skills: ['Go', 'PostgreSQL', 'Docker'],
        role: 'MEMBER',
        status: 'ACTIVE',
        joinedAt: '2026-09-01T15:00:00.000Z',
      },
    ],
    invitations: [],
    submissionStatus: 'SUBMITTED',
    submissionTitle: 'ForgeZK: Verifiable Parallel Rollup Sequencer',
    createdAt: '2026-09-01T10:30:00.000Z',
    updatedAt: '2026-09-02T16:00:00.000Z',
  },
  {
    id: 'team_neuralguard',
    hackathonId: 'htf-2026',
    name: 'NeuralGuard',
    slug: 'neuralguard',
    description: 'Autonomous security & red-teaming agents for smart contracts and LLM workflows.',
    trackId: 'trk_2',
    trackName: 'AI Safety & Intelligent Workflows',
    status: 'ACTIVE',
    sizeStatus: 'COMPLETE',
    memberCount: 3,
    minTeamSize: 2,
    maxTeamSize: 4,
    captain: {
      id: 'mem_5',
      userId: 'usr_priya',
      name: 'Priya Patel',
      email: 'priya.patel@bits-pilani.ac.in',
    },
    members: [
      {
        id: 'mem_5',
        userId: 'usr_priya',
        name: 'Priya Patel',
        username: 'priya_ml',
        email: 'priya.patel@bits-pilani.ac.in',
        college: 'BITS Pilani',
        branch: 'AI & Data Science',
        skills: ['PyTorch', 'Transformers', 'LangChain', 'Python'],
        role: 'CAPTAIN',
        status: 'ACTIVE',
        joinedAt: '2026-09-01T11:50:00.000Z',
      },
      {
        id: 'mem_6',
        userId: 'usr_meera',
        name: 'Meera Nambiar',
        username: 'meera_n',
        email: 'meera.nambiar@iitm.ac.in',
        college: 'IIT Madras',
        branch: 'Computer Science',
        skills: ['Vector Databases', 'FastAPI', 'Next.js'],
        role: 'MEMBER',
        status: 'ACTIVE',
        joinedAt: '2026-09-01T17:20:00.000Z',
      },
      {
        id: 'mem_7',
        userId: 'usr_tushar',
        name: 'Tushar Sen',
        username: 'tushar_sec',
        email: 'tushar.sen@iiitb.ac.in',
        college: 'IIIT Bangalore',
        branch: 'Information Technology',
        skills: ['Foundry', 'Python', 'Security Audits'],
        role: 'MEMBER',
        status: 'ACTIVE',
        joinedAt: '2026-09-01T18:00:00.000Z',
      },
    ],
    invitations: [
      {
        id: 'inv_1',
        inviteeUserId: 'usr_sneha',
        inviteeName: 'Sneha Reddy',
        inviteeEmail: 'sneha.reddy@stanford.edu',
        status: 'PENDING',
        createdAt: '2026-09-02T14:00:00.000Z',
      },
    ],
    submissionStatus: 'DRAFT',
    submissionTitle: 'NeuralAudit: Multi-Agent Formal Verification Engine',
    createdAt: '2026-09-01T11:50:00.000Z',
    updatedAt: '2026-09-02T14:00:00.000Z',
  },
  {
    id: 'team_nexus',
    hackathonId: 'htf-2026',
    name: 'Nexus Labs',
    slug: 'nexus-labs',
    description: 'Hardware keystores for trustless IoT edge telemetry.',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    status: 'ACTIVE',
    sizeStatus: 'COMPLETE',
    memberCount: 2,
    minTeamSize: 2,
    maxTeamSize: 4,
    captain: {
      id: 'mem_8',
      userId: 'usr_vikram',
      name: 'Vikram Malhotra',
      email: 'vikram.m@iitb.ac.in',
    },
    members: [
      {
        id: 'mem_8',
        userId: 'usr_vikram',
        name: 'Vikram Malhotra',
        username: 'vikram_m',
        email: 'vikram.m@iitb.ac.in',
        college: 'IIT Bombay',
        branch: 'Electrical Engineering',
        skills: ['C++', 'Embedded Systems', 'Rust'],
        role: 'CAPTAIN',
        status: 'ACTIVE',
        joinedAt: '2026-09-01T14:10:00.000Z',
      },
      {
        id: 'mem_9',
        userId: 'usr_kabir',
        name: 'Kabir Mehta',
        username: 'kabir_m',
        email: 'kabir.mehta@coep.ac.in',
        college: 'COEP Pune',
        branch: 'Instrumentation & IoT',
        skills: ['Hardware', 'C', 'Firmware', 'WebSockets'],
        role: 'MEMBER',
        status: 'ACTIVE',
        joinedAt: '2026-09-01T16:20:00.000Z',
      },
    ],
    invitations: [],
    submissionStatus: 'NONE',
    createdAt: '2026-09-01T14:10:00.000Z',
    updatedAt: '2026-09-01T16:20:00.000Z',
  },
  {
    id: 'team_zerotrace',
    hackathonId: 'htf-2026',
    name: 'ZeroTrace Privacy',
    slug: 'zerotrace',
    description: 'Compliant privacy pool using zk-SNARKs and selective disclosure credentials.',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    status: 'ACTIVE',
    sizeStatus: 'BELOW_MIN',
    memberCount: 1,
    minTeamSize: 2,
    maxTeamSize: 4,
    captain: {
      id: 'mem_10',
      userId: 'usr_aditya',
      name: 'Aditya Rao',
      email: 'aditya.rao@manipal.edu',
    },
    members: [
      {
        id: 'mem_10',
        userId: 'usr_aditya',
        name: 'Aditya Rao',
        username: 'aditya_zk',
        email: 'aditya.rao@manipal.edu',
        college: 'Manipal Institute of Technology',
        branch: 'Computer Science',
        skills: ['Rust', 'Circom', 'Solidity'],
        role: 'CAPTAIN',
        status: 'ACTIVE',
        joinedAt: '2026-09-02T10:00:00.000Z',
      },
    ],
    invitations: [],
    submissionStatus: 'NONE',
    createdAt: '2026-09-02T10:00:00.000Z',
    updatedAt: '2026-09-02T10:00:00.000Z',
  },
  {
    id: 'team_depin_sentinel',
    hackathonId: 'htf-2026',
    name: 'DePIN Sentinel',
    slug: 'depin-sentinel',
    description: 'Decentralized physical infrastructure network monitoring bandwidth and proof-of-uptime.',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    status: 'LOCKED',
    sizeStatus: 'FULL',
    memberCount: 4,
    minTeamSize: 2,
    maxTeamSize: 4,
    captain: {
      id: 'mem_11',
      userId: 'usr_harsh',
      name: 'Harsh Vardhan',
      email: 'harsh.v@iitr.ac.in',
    },
    members: [
      {
        id: 'mem_11',
        userId: 'usr_harsh',
        name: 'Harsh Vardhan',
        username: 'harsh_v',
        email: 'harsh.v@iitr.ac.in',
        college: 'IIT Roorkee',
        branch: 'Computer Science',
        skills: ['Go', 'Libp2p', 'Rust'],
        role: 'CAPTAIN',
        status: 'ACTIVE',
        joinedAt: '2026-09-01T09:00:00.000Z',
      },
      {
        id: 'mem_12',
        userId: 'usr_tanvi',
        name: 'Tanvi Joshi',
        username: 'tanvi_j',
        email: 'tanvi.j@vjti.ac.in',
        college: 'VJTI Mumbai',
        branch: 'Information Technology',
        skills: ['TypeScript', 'GraphQL', 'Next.js'],
        role: 'MEMBER',
        status: 'ACTIVE',
        joinedAt: '2026-09-01T10:00:00.000Z',
      },
      {
        id: 'mem_13',
        userId: 'usr_neil',
        name: 'Neil D’Souza',
        username: 'neil_d',
        email: 'neil.dsouza@pes.edu',
        college: 'PES University',
        branch: 'Computer Science',
        skills: ['Python', 'TimescaleDB', 'Docker'],
        role: 'MEMBER',
        status: 'ACTIVE',
        joinedAt: '2026-09-01T11:00:00.000Z',
      },
      {
        id: 'mem_14',
        userId: 'usr_ishaan',
        name: 'Ishaan Gupta',
        username: 'ishaan_g',
        email: 'ishaan.gupta@iiitd.ac.in',
        college: 'IIIT Delhi',
        branch: 'Computer Science',
        skills: ['Rust', 'Wasm', 'P2P'],
        role: 'MEMBER',
        status: 'ACTIVE',
        joinedAt: '2026-09-01T11:30:00.000Z',
      },
    ],
    invitations: [],
    submissionStatus: 'SUBMITTED',
    submissionTitle: 'SentinelNet: Decentralized Verifiable Uptime Oracles',
    createdAt: '2026-09-01T09:00:00.000Z',
    updatedAt: '2026-09-02T15:00:00.000Z',
  },
];

export const MOCK_UNASSIGNED_PARTICIPANTS: UnassignedParticipantItem[] = [
  {
    id: 'unassigned_1',
    userId: 'usr_rohan',
    name: 'Rohan Deshmukh',
    username: 'rohan_d',
    email: 'rohan.deshmukh@iiit.ac.in',
    college: 'IIIT Hyderabad',
    branch: 'Computer Science & Systems',
    skills: ['Go', 'Kubernetes', 'gRPC', 'PostgreSQL'],
    trackName: 'Open Innovation / Systems',
    registeredAt: '2026-09-02T08:20:00.000Z',
  },
  {
    id: 'unassigned_2',
    userId: 'usr_arjun',
    name: 'Arjun Verma',
    username: 'arjun_v',
    email: 'arjun.verma@vit.ac.in',
    college: 'VIT Vellore',
    branch: 'Computer Science & Engineering',
    skills: ['React Native', 'Node.js', 'TailwindCSS'],
    trackName: 'Open Innovation / Systems',
    registeredAt: '2026-09-02T15:00:00.000Z',
  },
  {
    id: 'unassigned_3',
    userId: 'usr_sneha',
    name: 'Sneha Reddy',
    username: 'sneha_sec',
    email: 'sneha.reddy@stanford.edu',
    college: 'Stanford University',
    branch: 'Computer Science (Cybersecurity)',
    skills: ['Formal Verification', 'Solidity', 'Foundry'],
    trackName: 'AI Safety & Intelligent Workflows',
    registeredAt: '2026-09-02T13:45:00.000Z',
  },
  {
    id: 'unassigned_4',
    userId: 'usr_shreya',
    name: 'Shreya Kapoor',
    username: 'shreya_k',
    email: 'shreya.k@nsut.ac.in',
    college: 'NSUT Delhi',
    branch: 'Data Science & Analytics',
    skills: ['Python', 'PyTorch', 'FastAPI', 'Pandas'],
    trackName: 'AI Safety & Intelligent Workflows',
    registeredAt: '2026-09-02T16:10:00.000Z',
  },
  {
    id: 'unassigned_5',
    userId: 'usr_pranav',
    name: 'Pranav Bhat',
    username: 'pranav_b',
    email: 'pranav.bhat@rvce.edu.in',
    college: 'RV College of Engineering',
    branch: 'Information Science',
    skills: ['TypeScript', 'Solidity', 'GraphQL', 'Next.js'],
    trackName: 'Open Innovation / Systems',
    registeredAt: '2026-09-02T17:00:00.000Z',
  },
];

export const MOCK_TEAM_METRICS: TeamMetrics = {
  totalTeams: 5,
  completeTeams: 4,
  incompleteTeams: 1,
  soloTeams: 1,
  unassignedParticipants: 5,
  belowMinTeams: 1,
};
