import { SubmissionItem, SubmissionMetrics } from './submissions-types';

export const MOCK_SUBMISSIONS: SubmissionItem[] = [
  {
    id: 'sub_forgezk',
    hackathonId: 'htf-2026',
    teamId: 'team_byteforge',
    teamName: 'ByteForge',
    teamSlug: 'byteforge',
    teamMembers: [
      { id: 'mem_1', userId: 'usr_aarav', name: 'Aarav Sharma', role: 'CAPTAIN' },
      { id: 'mem_2', userId: 'usr_ananya', name: 'Ananya Iyer', role: 'MEMBER' },
      { id: 'mem_3', userId: 'usr_dev', name: 'Devika Krishnan', role: 'MEMBER' },
      { id: 'mem_4', userId: 'usr_siddharth', name: 'Siddharth Roy', role: 'MEMBER' },
    ],
    title: 'ForgeZK: Verifiable Parallel Rollup Sequencer',
    description:
      'High-throughput zero-knowledge rollup sequencer written in Rust with parallel STARK prover generation and decentralized consensus verification on sovereign state machines.',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    status: 'FINALIZED',
    repository: {
      id: 'repo_forgezk',
      fullName: 'byteforge-labs/forge-zk-sequencer',
      url: 'https://github.com/byteforge-labs/forge-zk-sequencer',
      defaultBranch: 'main',
      commitSha: '8f4d9b231a4c',
      isVerified: true,
      pushedAt: '2026-09-02T15:45:00.000Z',
    },
    demoUrl: 'https://demo.forgezk.dev',
    documentationUrl: 'https://docs.forgezk.dev/architecture',
    videoUrl: 'https://youtube.com/watch?v=sample-forgezk',
    submittedAt: '2026-09-02T16:00:00.000Z',
    isLate: false,
    checks: {
      descriptionComplete: true,
      repositoryConnected: true,
      demoUrlProvided: true,
      onTimeSubmission: true,
      integrityPassed: true,
    },
    integrityScore: 98,
    integrityStatus: 'PASSED',
    createdAt: '2026-09-01T12:00:00.000Z',
    updatedAt: '2026-09-02T16:00:00.000Z',
  },
  {
    id: 'sub_neuralaudit',
    hackathonId: 'htf-2026',
    teamId: 'team_neuralguard',
    teamName: 'NeuralGuard',
    teamSlug: 'neuralguard',
    teamMembers: [
      { id: 'mem_5', userId: 'usr_priya', name: 'Priya Patel', role: 'CAPTAIN' },
      { id: 'mem_6', userId: 'usr_meera', name: 'Meera Nambiar', role: 'MEMBER' },
      { id: 'mem_7', userId: 'usr_tushar', name: 'Tushar Sen', role: 'MEMBER' },
    ],
    title: 'NeuralAudit: Multi-Agent Formal Verification Engine',
    description:
      'Autonomous red-teaming security network orchestrating specialized LLM agents and SMT solvers to uncover reentrancy, oracle manipulation, and logic vulnerabilities before smart contract deployment.',
    trackId: 'trk_2',
    trackName: 'AI Safety & Intelligent Workflows',
    status: 'SUBMITTED',
    repository: {
      id: 'repo_neuralaudit',
      fullName: 'neuralguard/neural-audit-agent',
      url: 'https://github.com/neuralguard/neural-audit-agent',
      defaultBranch: 'main',
      commitSha: '3e1b7c89a01f',
      isVerified: true,
      pushedAt: '2026-09-02T14:30:00.000Z',
    },
    demoUrl: 'https://neuralaudit.cloud',
    documentationUrl: 'https://github.com/neuralguard/neural-audit-agent#readme',
    videoUrl: 'https://loom.com/share/neuralaudit-demo',
    submittedAt: '2026-09-02T14:00:00.000Z',
    isLate: false,
    checks: {
      descriptionComplete: true,
      repositoryConnected: true,
      demoUrlProvided: true,
      onTimeSubmission: true,
      integrityPassed: true,
    },
    integrityScore: 96,
    integrityStatus: 'PASSED',
    createdAt: '2026-09-01T13:00:00.000Z',
    updatedAt: '2026-09-02T14:00:00.000Z',
  },
  {
    id: 'sub_sentinelnet',
    hackathonId: 'htf-2026',
    teamId: 'team_depin_sentinel',
    teamName: 'DePIN Sentinel',
    teamSlug: 'depin-sentinel',
    teamMembers: [
      { id: 'mem_11', userId: 'usr_harsh', name: 'Harsh Vardhan', role: 'CAPTAIN' },
      { id: 'mem_12', userId: 'usr_tanvi', name: 'Tanvi Joshi', role: 'MEMBER' },
      { id: 'mem_13', userId: 'usr_neil', name: 'Neil D’Souza', role: 'MEMBER' },
      { id: 'mem_14', userId: 'usr_ishaan', name: 'Ishaan Gupta', role: 'MEMBER' },
    ],
    title: 'SentinelNet: Decentralized Verifiable Uptime Oracles',
    description:
      'P2P edge telemetry mesh measuring cryptographic proof-of-bandwidth and latency benchmarks for decentralized cloud nodes with zero trust relay protocol.',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    status: 'FINALIZED',
    repository: {
      id: 'repo_sentinelnet',
      fullName: 'sentinelnet/depin-uptime-oracle',
      url: 'https://github.com/sentinelnet/depin-uptime-oracle',
      defaultBranch: 'main',
      commitSha: '6c2a4f109b8d',
      isVerified: true,
      pushedAt: '2026-09-02T17:10:00.000Z',
    },
    demoUrl: 'https://sentinel-net.network',
    documentationUrl: 'https://sentinel-net.network/docs',
    submittedAt: '2026-09-02T17:12:00.000Z',
    isLate: true,
    lateDurationMinutes: 12,
    checks: {
      descriptionComplete: true,
      repositoryConnected: true,
      demoUrlProvided: true,
      onTimeSubmission: false,
      integrityPassed: true,
    },
    integrityScore: 94,
    integrityStatus: 'PASSED',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-02T17:12:00.000Z',
  },
  {
    id: 'sub_telemetry_keystore',
    hackathonId: 'htf-2026',
    teamId: 'team_nexus',
    teamName: 'Nexus Labs',
    teamSlug: 'nexus-labs',
    teamMembers: [
      { id: 'mem_8', userId: 'usr_vikram', name: 'Vikram Malhotra', role: 'CAPTAIN' },
      { id: 'mem_9', userId: 'usr_kabir', name: 'Kabir Mehta', role: 'MEMBER' },
    ],
    title: 'Hardware Keystores for Trustless IoT Telemetry',
    description:
      'Low-power secure enclave firmware that signs sensor readings at the hardware boundary before publishing to decentralized storage layers.',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    status: 'DRAFT',
    repository: {
      id: 'repo_nexus_keystore',
      fullName: 'nexus-labs/hardware-keystore-iot',
      url: 'https://github.com/nexus-labs/hardware-keystore-iot',
      defaultBranch: 'main',
      commitSha: '9b3f1a24d87e',
      isVerified: false,
      pushedAt: '2026-09-02T11:00:00.000Z',
    },
    demoUrl: null,
    documentationUrl: 'https://github.com/nexus-labs/hardware-keystore-iot#readme',
    submittedAt: null,
    isLate: false,
    checks: {
      descriptionComplete: true,
      repositoryConnected: true,
      demoUrlProvided: false,
      onTimeSubmission: true,
      integrityPassed: true,
    },
    integrityScore: 91,
    integrityStatus: 'PASSED',
    createdAt: '2026-09-01T15:00:00.000Z',
    updatedAt: '2026-09-02T11:00:00.000Z',
  },
  {
    id: 'sub_zerotrace_pool',
    hackathonId: 'htf-2026',
    teamId: 'team_zerotrace',
    teamName: 'ZeroTrace Privacy',
    teamSlug: 'zerotrace',
    teamMembers: [
      { id: 'mem_10', userId: 'usr_aditya', name: 'Aditya Rao', role: 'CAPTAIN' },
    ],
    title: 'ZeroTrace Compliant Privacy Pool',
    description:
      'Zero-knowledge privacy pool utilizing Groth16 zk-SNARK proofs and selective disclosure verifiable credentials for sanctioned-address screening.',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    status: 'UNDER_REVIEW',
    repository: {
      id: 'repo_zerotrace',
      fullName: 'zerotrace/compliant-privacy-pool',
      url: 'https://github.com/zerotrace/compliant-privacy-pool',
      defaultBranch: 'main',
      commitSha: '1a9e8d4f2b3c',
      isVerified: true,
      pushedAt: '2026-09-02T13:15:00.000Z',
    },
    demoUrl: 'https://zerotrace.app',
    documentationUrl: null,
    submittedAt: '2026-09-02T13:30:00.000Z',
    isLate: false,
    checks: {
      descriptionComplete: true,
      repositoryConnected: true,
      demoUrlProvided: true,
      onTimeSubmission: true,
      integrityPassed: false,
    },
    integrityScore: 78,
    integrityStatus: 'FLAGGED',
    createdAt: '2026-09-02T10:00:00.000Z',
    updatedAt: '2026-09-02T13:30:00.000Z',
  },
];

export const MOCK_SUBMISSION_METRICS: SubmissionMetrics = {
  total: 5,
  submitted: 4,
  drafts: 1,
  readyForJudging: 3,
  needsAttention: 2,
  late: 1,
};
