import { ParticipantItem, RegistrationMetrics } from './registrations-types';

export const MOCK_PARTICIPANTS: ParticipantItem[] = [
  {
    id: 'reg_01',
    userId: 'usr_aarav',
    name: 'Aarav Sharma',
    username: 'aarav_sharma',
    email: 'aarav.sharma@iitd.ac.in',
    status: 'APPROVED',
    registeredAt: '2026-09-01T10:15:00.000Z',
    college: 'IIT Delhi',
    branch: 'Computer Science and Engineering',
    gradYear: 2026,
    skills: ['Rust', 'Distributed Systems', 'Zero-Knowledge', 'Solidity'],
    bio: 'Systems engineer passionate about verifiable compute and high-throughput consensus engines.',
    githubHandle: 'aarav-sharma-dev',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    teamId: 'team_byteforge',
    teamName: 'ByteForge',
    teamRole: 'CAPTAIN',
    teamMemberCount: 4,
    teamStatus: 'ACTIVE',
    checkInStatus: true,
  },
  {
    id: 'reg_02',
    userId: 'usr_priya',
    name: 'Priya Patel',
    username: 'priya_ml',
    email: 'priya.patel@bits-pilani.ac.in',
    status: 'APPROVED',
    registeredAt: '2026-09-01T11:42:00.000Z',
    college: 'BITS Pilani',
    branch: 'Artificial Intelligence & Data Science',
    gradYear: 2025,
    skills: ['PyTorch', 'Transformers', 'LangChain', 'CUDA', 'Python'],
    bio: 'Building autonomous verification agents for automated smart contract security audits.',
    githubHandle: 'priyapatel-ai',
    trackId: 'trk_2',
    trackName: 'AI Safety & Intelligent Workflows',
    teamId: 'team_neuralguard',
    teamName: 'NeuralGuard',
    teamRole: 'CAPTAIN',
    teamMemberCount: 3,
    teamStatus: 'ACTIVE',
    checkInStatus: true,
  },
  {
    id: 'reg_03',
    userId: 'usr_rohan',
    name: 'Rohan Deshmukh',
    username: 'rohan_d',
    email: 'rohan.deshmukh@iiit.ac.in',
    status: 'PENDING',
    registeredAt: '2026-09-02T08:20:00.000Z',
    college: 'IIIT Hyderabad',
    branch: 'Computer Science & Systems',
    gradYear: 2026,
    skills: ['Go', 'Kubernetes', 'gRPC', 'PostgreSQL', 'Docker'],
    bio: 'Fullstack cloud-native builder experimenting with edge consensus protocols.',
    githubHandle: 'rohand-codes',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    teamId: undefined,
    teamName: undefined,
    teamRole: undefined,
    teamMemberCount: 0,
    teamStatus: undefined,
    checkInStatus: false,
  },
  {
    id: 'reg_04',
    userId: 'usr_ananya',
    name: 'Ananya Iyer',
    username: 'ananya_ux',
    email: 'ananya.iyer@nitt.edu',
    status: 'PENDING',
    registeredAt: '2026-09-02T09:12:00.000Z',
    college: 'NIT Trichy',
    branch: 'Information Technology',
    gradYear: 2027,
    skills: ['React', 'Next.js', 'TailwindCSS', 'Figma', 'TypeScript'],
    bio: 'Product engineer passionate about accessible interfaces and realtime collaborative canvas tools.',
    githubHandle: 'ananya-iyer',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    teamId: 'team_byteforge',
    teamName: 'ByteForge',
    teamRole: 'MEMBER',
    teamMemberCount: 4,
    teamStatus: 'ACTIVE',
    checkInStatus: false,
  },
  {
    id: 'reg_05',
    userId: 'usr_vikram',
    name: 'Vikram Malhotra',
    username: 'vikram_m',
    email: 'vikram.m@iitb.ac.in',
    status: 'APPROVED',
    registeredAt: '2026-09-01T14:05:00.000Z',
    college: 'IIT Bombay',
    branch: 'Electrical Engineering & Signal Processing',
    gradYear: 2025,
    skills: ['C++', 'Embedded Systems', 'IoT', 'Rust', 'WebAssembly'],
    bio: 'Hardware & embedded hacker connecting cryptographic hardware keystores to decentralized networks.',
    githubHandle: 'vmalhotra-ee',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    teamId: 'team_nexus',
    teamName: 'Nexus Labs',
    teamRole: 'CAPTAIN',
    teamMemberCount: 2,
    teamStatus: 'ACTIVE',
    checkInStatus: true,
  },
  {
    id: 'reg_06',
    userId: 'usr_sneha',
    name: 'Sneha Reddy',
    username: 'sneha_sec',
    email: 'sneha.reddy@stanford.edu',
    status: 'WAITLISTED',
    registeredAt: '2026-09-02T13:45:00.000Z',
    college: 'Stanford University',
    branch: 'Computer Science (Cybersecurity)',
    gradYear: 2026,
    skills: ['Formal Verification', 'Solidity', 'Foundry', 'Python', 'Cryptography'],
    bio: 'Security researcher auditing zk-SNARK constraint systems and cross-chain message bridges.',
    githubHandle: 'snehareddy-sec',
    trackId: 'trk_2',
    trackName: 'AI Safety & Intelligent Workflows',
    teamId: undefined,
    teamName: undefined,
    teamRole: undefined,
    teamMemberCount: 0,
    teamStatus: undefined,
    checkInStatus: false,
  },
  {
    id: 'reg_07',
    userId: 'usr_karan',
    name: 'Karan Singhania',
    username: 'karan_s',
    email: 'karan.singhania@dtu.ac.in',
    status: 'REJECTED',
    registeredAt: '2026-09-01T16:30:00.000Z',
    college: 'Delhi Technological University',
    branch: 'Mechanical Engineering',
    gradYear: 2023,
    skills: ['JavaScript', 'HTML', 'CSS'],
    bio: 'Alumni participant seeking freelance projects.',
    githubHandle: 'karans-dtu',
    trackId: undefined,
    trackName: undefined,
    teamId: undefined,
    teamName: undefined,
    teamRole: undefined,
    teamMemberCount: 0,
    teamStatus: undefined,
    checkInStatus: false,
    rejectionReason: 'Does not satisfy student graduation year eligibility requirement (Graduated 2023).',
  },
  {
    id: 'reg_08',
    userId: 'usr_meera',
    name: 'Meera Nambiar',
    username: 'meera_n',
    email: 'meera.nambiar@iitm.ac.in',
    status: 'APPROVED',
    registeredAt: '2026-09-01T17:10:00.000Z',
    college: 'IIT Madras',
    branch: 'Computer Science',
    gradYear: 2026,
    skills: ['PyTorch', 'Vector Databases', 'FastAPI', 'Next.js', 'PostgreSQL'],
    bio: 'Building semantic retrieval graphs over technical papers and developer documentation.',
    githubHandle: 'meera-n-ai',
    trackId: 'trk_2',
    trackName: 'AI Safety & Intelligent Workflows',
    teamId: 'team_neuralguard',
    teamName: 'NeuralGuard',
    teamRole: 'MEMBER',
    teamMemberCount: 3,
    teamStatus: 'ACTIVE',
    checkInStatus: true,
  },
  {
    id: 'reg_09',
    userId: 'usr_arjun',
    name: 'Arjun Verma',
    username: 'arjun_v',
    email: 'arjun.verma@vit.ac.in',
    status: 'PENDING',
    registeredAt: '2026-09-02T15:00:00.000Z',
    college: 'VIT Vellore',
    branch: 'Computer Science & Engineering',
    gradYear: 2027,
    skills: ['React Native', 'Node.js', 'GraphQL', 'TailwindCSS'],
    bio: 'Mobile dev excited to build cross-platform decentralized identity wallets.',
    githubHandle: 'arjun-v-vit',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    teamId: undefined,
    teamName: undefined,
    teamRole: undefined,
    teamMemberCount: 0,
    teamStatus: undefined,
    checkInStatus: false,
  },
  {
    id: 'reg_10',
    userId: 'usr_dev',
    name: 'Devika Krishnan',
    username: 'devika_k',
    email: 'devika.krishnan@iitk.ac.in',
    status: 'APPROVED',
    registeredAt: '2026-09-01T18:40:00.000Z',
    college: 'IIT Kanpur',
    branch: 'Computer Science & Mathematics',
    gradYear: 2025,
    skills: ['ZK-Rollups', 'Rust', 'Circom', 'Solidity', 'Cryptography'],
    bio: 'Exploring succinct proof verification in resource-constrained execution environments.',
    githubHandle: 'devika-k-zk',
    trackId: 'trk_1',
    trackName: 'Open Innovation / Systems',
    teamId: 'team_byteforge',
    teamName: 'ByteForge',
    teamRole: 'MEMBER',
    teamMemberCount: 4,
    teamStatus: 'ACTIVE',
    checkInStatus: true,
  },
];

export const MOCK_REGISTRATION_METRICS: RegistrationMetrics = {
  total: 48,
  pending: 12,
  approved: 32,
  rejected: 2,
  waitlisted: 2,
  checkedIn: 28,
};
