import {
  JudgeItem,
  SubmissionJudgingItem,
  EvaluationItem,
  JudgingMetrics,
} from './judging-types';
import { JudgingCriterionEntity } from '@almosthack/types';

export const MOCK_CRITERIA: JudgingCriterionEntity[] = [
  {
    id: 'crit_tech',
    hackathonId: 'htf-2026',
    name: 'Technical Implementation & Architecture',
    description: 'Code quality, system complexity, robust verification, and engineering precision.',
    weight: 0.4,
    maxScore: 40,
    displayOrder: 1,
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'crit_originality',
    hackathonId: 'htf-2026',
    name: 'Originality & Novelty',
    description: 'Uniqueness of approach, creative problem solving, and breakthrough mechanisms.',
    weight: 0.25,
    maxScore: 25,
    displayOrder: 2,
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'crit_impact',
    hackathonId: 'htf-2026',
    name: 'Feasibility & Real-world Impact',
    description: 'Practical adoption potential, market utility, and tangible ecosystem value.',
    weight: 0.2,
    maxScore: 20,
    displayOrder: 3,
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'crit_presentation',
    hackathonId: 'htf-2026',
    name: 'Documentation & Demo Polish',
    description: 'Clarity of walkthrough pitch, live demo responsiveness, and documentation depth.',
    weight: 0.15,
    maxScore: 15,
    displayOrder: 4,
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
];

export const MOCK_JUDGES: JudgeItem[] = [
  {
    id: 'judge_1',
    userId: 'usr_jdg_aris',
    name: 'Dr. Aris Thorne',
    email: 'aris.thorne@hyperion.research',
    avatarUrl: undefined,
    title: 'Principal Systems Architect',
    organization: 'Hyperion Research Labs',
    assignedCount: 4,
    completedCount: 4,
    remainingCount: 0,
    completionRate: 100,
    status: 'COMPLETED',
    isCalibrated: true,
    averageScoreGiven: 89.5,
    conflicts: [],
  },
  {
    id: 'judge_2',
    userId: 'usr_jdg_priya',
    name: 'Priya Sharma',
    email: 'priya.sharma@nexus-vc.io',
    avatarUrl: undefined,
    title: 'Managing Partner',
    organization: 'Nexus Early Stage Fund',
    assignedCount: 4,
    completedCount: 3,
    remainingCount: 1,
    completionRate: 75,
    status: 'ON_TRACK',
    isCalibrated: true,
    averageScoreGiven: 84.0,
    conflicts: [
      {
        submissionId: 'sub_telemetry_keystore',
        projectTitle: 'Hardware Keystores for Trustless IoT Telemetry',
        reason: 'Advisor to Nexus Labs member',
      },
    ],
  },
  {
    id: 'judge_3',
    userId: 'usr_jdg_vikram',
    name: 'Vikramaditya Sen',
    email: 'vikram.sen@berkeley.edu',
    avatarUrl: undefined,
    title: 'Adjunct Professor, Cryptography',
    organization: 'UC Berkeley',
    assignedCount: 4,
    completedCount: 2,
    remainingCount: 2,
    completionRate: 50,
    status: 'ON_TRACK',
    isCalibrated: true,
    averageScoreGiven: 91.0,
    conflicts: [],
  },
  {
    id: 'judge_4',
    userId: 'usr_jdg_elena',
    name: 'Elena Rostova',
    email: 'elena.r@open-ai.foundation',
    avatarUrl: undefined,
    title: 'Lead AI Safety Researcher',
    organization: 'Open Intelligence Foundation',
    assignedCount: 3,
    completedCount: 1,
    remainingCount: 2,
    completionRate: 33,
    status: 'BEHIND',
    isCalibrated: true,
    averageScoreGiven: 82.0,
    conflicts: [],
  },
];

export const MOCK_SUBMISSION_JUDGING: SubmissionJudgingItem[] = [
  {
    id: 'sj_forgezk',
    submissionId: 'sub_forgezk',
    projectTitle: 'ForgeZK: Verifiable Parallel Rollup Sequencer',
    teamName: 'ByteForge',
    teamSlug: 'byteforge',
    trackName: 'Open Innovation / Systems',
    requiredEvaluations: 2,
    completedEvaluations: 2,
    assignedJudges: [
      { judgeId: 'judge_1', judgeName: 'Dr. Aris Thorne', status: 'COMPLETED', score: 94 },
      { judgeId: 'judge_3', judgeName: 'Vikramaditya Sen', status: 'COMPLETED', score: 92 },
    ],
    averageScore: 93.0,
    status: 'COMPLETE',
  },
  {
    id: 'sj_neuralaudit',
    submissionId: 'sub_neuralaudit',
    projectTitle: 'NeuralAudit: Multi-Agent Formal Verification Engine',
    teamName: 'NeuralGuard',
    teamSlug: 'neuralguard',
    trackName: 'AI Safety & Intelligent Workflows',
    requiredEvaluations: 2,
    completedEvaluations: 2,
    assignedJudges: [
      { judgeId: 'judge_2', judgeName: 'Priya Sharma', status: 'COMPLETED', score: 88 },
      { judgeId: 'judge_4', judgeName: 'Elena Rostova', status: 'COMPLETED', score: 82 },
    ],
    averageScore: 85.0,
    status: 'COMPLETE',
  },
  {
    id: 'sj_sentinelnet',
    submissionId: 'sub_sentinelnet',
    projectTitle: 'SentinelNet: Decentralized Verifiable Uptime Oracles',
    teamName: 'DePIN Sentinel',
    teamSlug: 'depin-sentinel',
    trackName: 'Open Innovation / Systems',
    requiredEvaluations: 2,
    completedEvaluations: 1,
    assignedJudges: [
      { judgeId: 'judge_1', judgeName: 'Dr. Aris Thorne', status: 'COMPLETED', score: 85 },
      { judgeId: 'judge_2', judgeName: 'Priya Sharma', status: 'IN_PROGRESS' },
    ],
    averageScore: 85.0,
    status: 'IN_PROGRESS',
  },
  {
    id: 'sj_zerotrace',
    submissionId: 'sub_zerotrace_pool',
    projectTitle: 'ZeroTrace Compliant Privacy Pool',
    teamName: 'ZeroTrace Privacy',
    teamSlug: 'zerotrace',
    trackName: 'Open Innovation / Systems',
    requiredEvaluations: 2,
    completedEvaluations: 0,
    assignedJudges: [
      { judgeId: 'judge_3', judgeName: 'Vikramaditya Sen', status: 'ASSIGNED' },
      { judgeId: 'judge_4', judgeName: 'Elena Rostova', status: 'ASSIGNED' },
    ],
    averageScore: undefined,
    status: 'IN_PROGRESS',
  },
];

export const MOCK_EVALUATIONS: EvaluationItem[] = [
  {
    id: 'eval_1',
    assignmentId: 'asgn_1',
    submissionId: 'sub_forgezk',
    projectTitle: 'ForgeZK: Verifiable Parallel Rollup Sequencer',
    teamName: 'ByteForge',
    judgeUserId: 'usr_jdg_aris',
    judgeName: 'Dr. Aris Thorne',
    status: 'SUBMITTED',
    totalScore: 94,
    maxScore: 100,
    generalFeedback:
      'Exceptional performance and clean concurrency primitives in the parallel prover pipeline. Benchmarks verified locally.',
    criterionScores: [
      {
        criterionId: 'crit_tech',
        criterionName: 'Technical Implementation & Architecture',
        score: 38,
        maxScore: 40,
        weight: 0.4,
        comment: 'Robust multithreaded STARK prover pipeline.',
      },
      {
        criterionId: 'crit_originality',
        criterionName: 'Originality & Novelty',
        score: 24,
        maxScore: 25,
        weight: 0.25,
        comment: 'Unique state decomposition model.',
      },
      {
        criterionId: 'crit_impact',
        criterionName: 'Feasibility & Real-world Impact',
        score: 18,
        maxScore: 20,
        weight: 0.2,
      },
      {
        criterionId: 'crit_presentation',
        criterionName: 'Documentation & Demo Polish',
        score: 14,
        maxScore: 15,
        weight: 0.15,
      },
    ],
    submittedAt: '2026-09-02T18:00:00.000Z',
    createdAt: '2026-09-02T17:30:00.000Z',
  },
  {
    id: 'eval_2',
    assignmentId: 'asgn_2',
    submissionId: 'sub_neuralaudit',
    projectTitle: 'NeuralAudit: Multi-Agent Formal Verification Engine',
    teamName: 'NeuralGuard',
    judgeUserId: 'usr_jdg_priya',
    judgeName: 'Priya Sharma',
    status: 'SUBMITTED',
    totalScore: 88,
    maxScore: 100,
    generalFeedback:
      'Very strong product-market fit for Web3 security auditing firms. Demo UI is crisp and provides actionable vulnerability trees.',
    criterionScores: [
      {
        criterionId: 'crit_tech',
        criterionName: 'Technical Implementation & Architecture',
        score: 34,
        maxScore: 40,
        weight: 0.4,
      },
      {
        criterionId: 'crit_originality',
        criterionName: 'Originality & Novelty',
        score: 23,
        maxScore: 25,
        weight: 0.25,
      },
      {
        criterionId: 'crit_impact',
        criterionName: 'Feasibility & Real-world Impact',
        score: 18,
        maxScore: 20,
        weight: 0.2,
      },
      {
        criterionId: 'crit_presentation',
        criterionName: 'Documentation & Demo Polish',
        score: 13,
        maxScore: 15,
        weight: 0.15,
      },
    ],
    submittedAt: '2026-09-02T18:45:00.000Z',
    createdAt: '2026-09-02T18:15:00.000Z',
  },
];

export const MOCK_JUDGING_METRICS: JudgingMetrics = {
  totalSubmissions: 4,
  requiredEvaluations: 8,
  completedEvaluations: 5,
  remainingEvaluations: 3,
  completionPercentage: 62.5,
  totalJudges: 4,
  calibratedJudges: 4,
  submissionsNeedingAttention: 2,
  activeConflicts: 1,
};
